before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - source "$HOME/.cargo/env"
  - rustup toolchain add stable
  - rustup toolchain add beta

build:
  script:
    - cargo build --verbose

test:
  script:
    - cargo test --verbose
    - cargo test --release --verbose