before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - source "$HOME/.cargo/env"

stable:
  script:
    - cargo +stable build --verbose
    - cargo +stable test --verbose
    - cargo +stable test --release --verbose

beta:
  script:
    - rustup toolchain add beta
    - cargo +beta build --verbose
    - cargo +beta test --verbose
    - cargo +beta test --release --verbose

nightly:
  script:
  - rustup toolchain add nightly
    - cargo +nightly build --verbose
    - cargo +nightly test --verbose
    - cargo +nightly test --release --verbose