before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - source "$HOME/.cargo/env"

build_stable:
  script:
    - cargo +stable build --verbose

test_stable:
  script:
    - bash -c "cargo test --verbose"
    - bash -c "cargo test --release --verbose"
    
build_beta:
  script:
    - rustup toolchain add beta
    - cargo +beta build --verbose

test_beta:
  script:
    - bash -c "cargo +beta test --verbose"
    - bash -c "cargo +beta test --release --verbose"

build_nightly:
  script:
    - rustup toolchain add nightly
    - cargo +nightly build --verbose

test_nightly:
  script:
    - bash -c "cargo +nightly test --verbose"
    - bash -c "cargo +nightly test --release --verbose"